
 /*
     *Podemos controlar la velocidad de la simulacion con el parametro
      "simulation.totalSteps" 
      la cantidad de turistas con el parametro "tourists"
        y la semilla para generar  numeros aleatorios con "simulation.seed"
     */

simulation.seed=42 
simulation.totalSteps=10
tourists=50
